@startuml
:用户: as User
left to right direction
User<|--决策者
User<|--服务人员
User<|--病人
User<|--管理员
rectangle 新型冠状肺炎病人信息管理系统{
(登录)--User
(注册)--User
病人--(健康打卡)
(健康打卡)<..(健康卡片):extend
(健康打卡)<..(服务登记):extend
(健康打卡)<..(就餐申报):extend
(健康打卡)<..(返程报备):extend
病人--(外出登记)
服务人员--(信息上报)
(信息上报)<..(疫情线索):extend
(信息上报)<..(健康状况):extend
决策者--(数据统计)
决策者--(汇总信息)
服务人员--(就餐信息)
服务人员--(物资信息)
(就餐信息).>(消息推送):extend
(物资信息).>(消息推送):extend
决策者--(决策分析)
(决策分析)<.(疫情规模分析):extend
管理员--(系统维护)
(系统维护)<..(添加用户信息):extend
(系统维护)<..(删除用户信息):extend
(系统维护)<..(修改用户信息):extend
}
@enduml