@startuml
left to right direction
用户-->(管理简历)
(管理简历).->(新增简历):<<include>>
(管理简历).->(删除简历):<<include>>
(管理简历).->(更改简历):<<include>>
用户-->(生成用户画像)
用户-->(管理个人信息)
用户-->(投递记录)
(投递记录).->(查看投递记录):<<include>>
用户-->(查看岗位信息)
(查看岗位信息).->(投递岗位):<<include>>
用户-->(匹配岗位)
(匹配岗位).->(投递岗位):<<include>>

(投递记录).->(生成职业分析报告):<<include>>
(生成职业分析报告).->(导出):<<include>>
用户-->(查看企业画像)
(查看企业画像).->(查询薪资):<<include>>

@enduml